### ISSUE TITLE
Click FAB button show briefly rectangle box around the round button

### ISSUE THREAD

**Issue by mulyoved** [fin-alg-com/orderio04#14]
https://www.loom.com/share/c690dbdd88ff4c91b0bc3018f3090efd

**Comment by skillnett** [comment]
https://user-images.githubusercontent.com/41345799/192271592-a96058a3-c3f7-4f4a-b6a3-4a0d28b5bc37.mp4

I've checked this behavior and this is an effect of chrome mobile view. If you open your app through any mobile device there will be everything ok
